export default class PresetEquationRunner {
    constructor(preset: any, globalVars: any, opts: any);
    preset: any;
    texsizeX: any;
    texsizeY: any;
    mesh_width: any;
    mesh_height: any;
    aspectx: any;
    aspecty: any;
    invAspectx: number;
    invAspecty: number;
    qs: any;
    ts: any;
    regs: any;
    initializeEquations(globalVars: any): void;
    runVertEQs: boolean;
    mdVSQInit: {};
    mdVSRegs: any;
    mdVSFrame: any;
    mdVSUserKeys: string[];
    mdVSFrameMap: any;
    mdVSShapes: any[];
    mdVSUserKeysShapes: any[];
    mdVSFrameMapShapes: any[];
    mdVSWaves: any[];
    mdVSUserKeysWaves: any[];
    mdVSFrameMapWaves: any[];
    mdVSQAfterFrame: {};
    gmegabuf: any;
    mdVS: any;
    mdVSTWaveInits: any[];
    mdVSTShapeInits: any[];
    updatePreset(preset: any, globalVars: any): void;
    updateGlobals(opts: any): void;
    runFrameEquations(globalVars: any): any;
    runPixelEquations(mdVSVertex: any): any;
    runShapeFrameEquations(shapeIdx: any, mdVSShape: any): any;
    runWaveFrameEquations(waveIdx: any, mdVSWave: any): any;
    runWavePointEquations(waveIdx: any, mdVSWaveFrame: any): any;
}
